// This script licensed under the MIT.
// http://orgachem.mit-license.org


var jsdocref = require('../../jsdocref');
var array = require('../array');
var BlockContent = require('./BlockContent');
var Paragraph = require('./Paragraph');
var Tag = require('./Tag');
var Link = require('./Link');
var VimHelpContainerPublisher = require('./VimHelpContainerPublisher');



/**
 * Base class for publishing container.
 * The structure is:
 * <ul>
 * <li>Top content
 * <li>Sub contents
 *   <ul>
 *   <li>sub content 1
 *   <li>Sub content 2
 *   <li>...
 *   </ul>
 * </ul>
 *
 * @param {string} caption Caption.
 * @param {?string=} opt_refId Optional reference ID.  The ID is generated by
 *     the {@code caption}, if not given {@code opt_refId}.
 * @param {?jsdocref.publishing.BlockContent=} opt_topContent Optional top
 *     content.
 * @param {?boolean=} opt_listed Optional flag that controls a visibility on a
 *     table of contents.
 * @constructor
 * @extends {jsdocref.publishing.BlockContent}
 */
var Container = function(caption, opt_refId, opt_topContent, opt_visible) {
  BlockContent.call(this);
  this.caption_ = caption;
  this.tag_ = new Tag(opt_refId || this.getReferenceId());
  this.setTopContent(opt_topContent);
  this.subContents_ = [];
  this.visibility_ = opt_visible || false;
};
jsdocref.inherits(Container, BlockContent);


/**
 * Default publisher for the container.
 * @type {jsdocref.publisher.VimHelpContainerPublisher}
 */
Container.publisher = VimHelpContainerPublisher.getInstance();


/**
 * Visibirity flag that controls a visibility on a table of contents.
 * @type {boolean}
 * @private
 */
Container.prototype.visibility_;


/**
 * Parent content.
 * @type {jsdocref.publishing.Content}
 * @private
 */
Container.prototype.parent_ = null;


/**
 * Caption of the container.
 * @type {string}
 * @private
 */
Container.prototype.caption_;


/**
 * Tag of the container.
 * @type {jsdocref.publishing.Tag}
 * @private
 */
Container.prototype.tag_;


/**
 * Top content in the container.
 * @type {jsdocref.publishing.Sentence}
 * @private
 */
Container.prototype.topContent_ = null;


/**
 * Sub contents of the container.
 * @type {Array.<jsdocref.publishing.BlockContent>}
 * @private
 */
Container.prototype.subContents_;


/**
 * Whether the container allows to be listed on a table of contents.
 * @return {boolean} Whether the container allows to be listed on a table of
 *     contents.
 */
Container.prototype.isVisibleOnContentsTable = function() {
  return this.visibility_;
};


/**
 * Returns a tag of the container.
 * @return {jsdocref.publishing.Tag} Tag of the container.
 */
Container.prototype.getTag = function() {
  return this.tag_;
};


/**
 * Returns descendant contents.
 * @return {Array.<jsdocref.publishing.Content>} Descendant contents.
 */
Container.prototype.getDescendants = function() {
  var descendants = [];
  this.getSubContents().forEach(function(sub) {
    descendants.push(sub);
    descendants = descendants.concat(sub.getDescendants());
  });

  return descendants;
};


/**
 * Returns ancestor contents.
 * @return {Array.<jsdocref.publishing.Content>} Ancestor contents.
 */
Container.prototype.getAncestors = function() {
  var ancestors = [];
  var current = this;

  while (current = current.getParent()) {
    ancestors.unshift(current);
  }

  return ancestors;
};


/**
 * Returns a depth of the container.
 * @return {number} Depth of the container.
 */
Container.prototype.getSelfDepth = function() {
  return this.getAncestors().length;
};


/**
 * Sets a parent content.  This method is chainable.
 * @param {jsdocref.publishing.Content} content Parent content.
 * @return {jsdocref.publishing.Container} This instance.
 * @protected
 */
Container.prototype.setParent = function(content) {
  this.parent_ = content;
  return this;
};


/**
 * Returns a parent content.
 * @return {jsdocref.publishing.Content} Parent content.
 */
Container.prototype.getParent = function() {
  return this.parent_;
};


/**
 * Returns a reference ID.
 * @return {string} Caption of the container.
 */
Container.prototype.getCaption = function() {
  return this.caption_;
};


/**
 * Returns an index number of the content.
 * @return {number} Index of the content.
 */
Container.prototype.getSelfIndex = function() {
  var parent;
  if (parent = this.getParent()) {
    return parent.getSubContents().indexOf(this);
  }

  return -1;
};


/**
 * Returns a reference ID.
 * @return {string} Reference ID.
 */
Container.prototype.getReferenceId = function() {
  return this.tag_ ? this.tag_.getReferenceId() : this.getReferenceIdInternal(
      this.getCaption());
};


/**
 * Returns a link to the container.
 * @return {jsdocref.publishing.Link} Link.
 */
Container.prototype.getLink = function() {
  return new Link(this.getReferenceId());
};


/**
 * Returns a reference ID by a caption.  This ID is made by the caption.  For
 * example, a caption that is {@code 'The caption example'} becomes {@code
 * 'the-caption-example'}.
 * @param {string} caption Caption.
 * @return {string} Reference ID.
 * @protected
 */
Container.prototype.getReferenceIdInternal = function(caption) {
  return caption.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/\s+/g, '-').
      toLowerCase();
};


/**
 * Sets a top content.  This method is chainable.
 * @param {jsdocref.publishing.BlockContent} content Top content.
 * @return {jsdocref.publishing.Container} This instance.
 */
Container.prototype.setTopContent = function(content) {
  this.topContent_ = content;
  return this;
};


/**
 * Returns a top content.
 * @return {jsdocref.publishing.BlockContent} Top content.
 */
Container.prototype.getTopContent = function() {
  return this.topContent_;
};


/**
 * Returns sub contents.
 * @return {Array.<jsdocref.publishing.BlockContent>} Sub contents.
 */
Container.prototype.getSubContents = function() {
  return array.clone(this.subContents_);
};


/**
 * Returns a sub content.
 * @param {number} index Index.
 * @return {jsdocref.publishing.BlockContent} Sub content.
 */
Container.prototype.getSubContentAt = function(index) {
  return this.getSubContents()[index];
};


/**
 * Appends a sub content to last.  This method is chainable.
 * @param {jsdocref.publishing.BlockContent} content Content to append.
 * @return {jsdocref.publishing.Container} This instance.
 */
Container.prototype.appendSubContent = function(content) {
  return this.appendSubContentAt(content, this.subContents_.length);
};


/**
 * Appends a sub content by an index.  This method is chainable.
 * @param {jsdocref.publishing.BlockContent} content Content to append.
 * @param {number} index Index.
 * @return {jsdocref.publishing.Container} This instance.
 */
Container.prototype.appendSubContentAt = function(content, index) {
  this.subContents_.splice(index, 0, content);
  if (content.setParent) {
    content.setParent(this);
  }
  return this;
};


/**
 * Removes a sub content by a content.
 * @param {jsdocref.publishing.BlockContent} content to remove.
 * @return {?jsdocref.publishing.BlockContent} Content was removed, if any.
 */
Container.prototype.removeSubContent = function(content) {
  var index;
  if ((index = this.subContents_.indexOf(content)) >= 0) {
    return this.removeSubContentAt(index);
  }
  return null;
};


/**
 * Removes a sub content by an index.
 * @param {number} index Index.
 * @return {?jsdocref.publishing.BlockContent} Content was removed, if any.
 */
Container.prototype.removeSubContentAt = function(index) {
  var removed;
  if (this.subContents_[index]) {
    removed = this.subContents_.splice(index, 1)[0];
    if (removed.setParent) {
      removed.setParent(null);
    }
    return removed;
  }

  return null;
};


// Exports the constructor.
module.exports = Container;
