// This script licensed under the MIT.
// http://orgachem.mit-license.org


var tsumekusa = require('../../tsumekusa');
var array = require('../array');
var Content = require('./Content');
var ContentArray = require('./ContentArray');
var Paragraph = require('./Paragraph');
var Tag = require('./Tag');
var Link = require('./Link');
var VimHelpContainerPublisher = require(
    '../publishing/vimhelp/VimHelpContainerPublisher');



/**
 * Base class for containers.  The container can be used as a chapter, section
 * and article.
 *
 * The structure is:
 * <ul>
 * <li>Caption
 * <li>Top contents
 *   <ul>
 *   <li>Container 1
 *   <li>Container 2
 *   <li>...
 *   </ul>
 * <li>Sub containers
 *   <ul>
 *   <li>Sub container 1
 *   <li>Sub container 2
 *   <li>...
 *   </ul>
 * </ul>
 *
 * @param {string} caption Caption.
 * @param {?string=} opt_refId Optional reference ID.  The ID is generated by
 *     the {@code caption}, if not given {@code opt_refId}.
 * @param {?boolean=} opt_visible Optional flag that controls a visibility on a
 *     table of contents.
 * @constructor
 * @extends {tsumekusa.contents.Content}
 */
var Container = function(caption, opt_refId, opt_visible) {
  Content.call(this);
  this.setCaption(caption);
  this.tag_ = new Tag(opt_refId || this.getReferenceId());
  this.topBlocks_ = new ContentArray();
  this.subContents_ = new ContentArray();
  this.visibility_ = opt_visible || false;
};
tsumekusa.inherits(Container, Content);


/**
 * Default publisher for the container.
 * @type {tsumekusa.publisher.VimHelpContainerPublisher}
 */
Container.publisher = VimHelpContainerPublisher.getInstance();


/**
 * Container as a parent of the content.
 * @type {tsumekusa.contents.Container}
 * @private
 */
Container.prototype.parent_ = null;


/**
 * Visibirity flag that controls a visibility on a table of contents.
 * @type {boolean}
 * @private
 */
Container.prototype.visibility_ = false;


/**
 * Caption of the container.
 * @type {string}
 * @private
 */
Container.prototype.caption_ = null;


/**
 * Tag of the container.
 * @type {tsumekusa.contents.Tag}
 * @private
 */
Container.prototype.tag_;


/**
 * Top contents of the container.
 * @type {tsumekusa.contents.ContentArray.<tsumekusa.contents.BlockContent>}
 * @private
 */
Container.prototype.topBlocks_ = null;


/**
 * Sub contents of the container.
 * @type {tsumekusa.contents.ContentArray.<tsumekusa.contents.BlockContent>}
 * @private
 */
Container.prototype.subContents_ = null;


/**
 * Whether the container allows to be listed on a table of contents.
 * @return {boolean} Whether the container allows to be listed on a table of
 *     contents.
 */
Container.prototype.isVisibleOnContentsTable = function() {
  return this.visibility_;
};


// Methods for a caption {{{
/**
 * Returns a caption of the container.
 * @return {string} Caption of the container.
 */
Container.prototype.getCaption = function() {
  return this.caption_;
};


/**
 * Sets a caption of the container.  This method is chainable.
 * @param {string} caption of the container.
 * @return {tsumekusa.contents.Container} This instance.
 */
Container.prototype.setCaption = function(caption) {
  this.caption_ = caption;
  return this;
};
//}}}


// Methods about reference to a container {{{
/**
 * Returns a tag of the container.
 * @return {tsumekusa.contents.Tag} Tag of the container.
 */
Container.prototype.getTag = function() {
  return this.tag_;
};


/**
 * Returns a link to the container.
 * @return {tsumekusa.contents.Link} Link.
 */
Container.prototype.getLink = function() {
  return new Link(this.getReferenceId());
};


/**
 * Returns a reference ID.
 * @return {string} Reference ID.
 */
Container.prototype.getReferenceId = function() {
  return this.tag_ ? this.tag_.getReferenceId() : this.getReferenceIdInternal(
      this.getCaption());
};


/**
 * Returns a reference ID by a caption.  This ID is made by the caption.  For
 * example, a caption that is {@code 'The caption example'} becomes {@code
 * 'the-caption-example'}.
 * @param {string} caption Caption.
 * @return {string} Reference ID.
 * @protected
 */
Container.prototype.getReferenceIdInternal = function(caption) {
  return caption.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/\s+/g, '-').
      toLowerCase();
};
//}}}


// Methods for a parent and children relationship {{{
/**
 * Returns a block content as a parent of the content.
 * @return {tsumekusa.contents.IContent} Parent content.
 */
Container.prototype.getParent = function() {
  return this.parent_;
};


/**
 * Sets a block content as parent.  This method is chainable.
 * @param {tsumekusa.contents.Container} parent Parent.
 * @return {tsumekusa.contents.Container} This instance.
 */
Container.prototype.setParent = function(parent) {
  this.parent_ = parent;
  return this;
};


/**
 * Returns ancestor block contents.
 * @return {Array.<tsumekusa.contents.Container>} Ancestor block contents.
 */
Container.prototype.getAncestors = function() {
  var ancestors = [];
  var current = this;

  while (current = current.getParent()) {
    ancestors.unshift(current);
  }

  return ancestors;
};


/**
 * Returns descendant contents.
 * @return {Array.<tsumekusa.contents.Container>} Descendant contents.
 */
Container.prototype.getDescendants = function() {
  var descendants = [];
  this.getSubContainers().getChildren().forEach(function(sub) {
    descendants.push(sub);
    descendants = descendants.concat(sub.getDescendants());
  });

  return descendants;
};


/**
 * Returns an index number of the content.
 * @return {number} Index of the content.
 */
Container.prototype.getIndex = function() {
  var parent;
  if (parent = this.getParent()) {
    return parent.getSubContainers().getChildren().indexOf(this);
  }

  return -1;
};


/**
 * Returns a depth of the container.
 * @return {number} Depth of the container.
 */
Container.prototype.getDepth = function() {
  return this.getAncestors().length;
};
//}}}


// Methods for top contents manipulation {{{
/**
 * Returns top block contents.
 * @return {tsumekusa.contents.ContentArray.<tsumekusa.contents.BlockContent>}
 *     Block contents on the top.
 */
Container.prototype.getTopContents = function() {
  return this.topBlocks_;
};
//}}}


// Methods for sub containers manipulation {{{
/**
 * Returns sub contents.
 * @return {tsumekusa.contents.ContentArray.<tsumekusa.contents.BlockContent>}
 *     Containers as children of the container.
 */
Container.prototype.getSubContainers = function() {
  return this.subContents_;
};


/**
 * Adds a sub container at the last.  This method is chainable.
 * @param {tsumekusa.contents.Container} container Sub container to add.
 * @return {tsumekusa.contents.Container} This instance.
 */
Container.prototype.addSubContainer = function(container) {
  container.setParent(this);
  this.subContents_.addChild(container);
  return this;
};


/**
 * Adds a sub container at the given 0-based index.  This method is chainable.
 * @param {tsumekusa.contents.Container} container Sub container to add.
 * @param {number} index 0-based index.
 * @return {tsumekusa.contents.Container} This instance.
 */
Container.prototype.addSubContainerAt = function(container, index) {
  container.setParent(this);
  this.subContents_.addChildAt(container, index);
  return this;
};


/**
 * Removes the specified sub container.
 * @param {tsumekusa.contents.Container} container Sub container to remove.
 * @return {tsumekusa.contents.Container} Removed sub container, if any.
 */
Container.prototype.removeSubContainer = function(container) {
  var removed = this.subContents_.removeChild(container);

  if (removed) {
    removed.setParent(null);
  }
  return removed;
};


/**
 * Removes the specified sub container at the given 0-based index.
 * @param {number} index 0-based index.
 * @return {tsumekusa.contents.Container} Removed sub container, if any.
 */
Container.prototype.removeSubContainerAt = function(index) {
  var removed = this.subContents_.removeChildAt(index);

  if (removed) {
    removed.setParent(null);
  }
  return removed;
};
//}}}

// Exports the constructor.
module.exports = Container;
