// This script licensed under the MIT.
// http://orgachem.mit-license.org


var tsumekusa = require('../../../tsumekusa');
var string = require('../../../tsumekusa/string');
var date = require('../../../tsumekusa/date');
var consoleDoc = require('../../../tsumekusa/consoleDoc');
var ConsoleContainerPublisher = require(
    '../../../tsumekusa/publishing/ConsoleContainerPublisher');



/**
 * A class for document publisher for console.
 * @constructor
 * @extends {ConsoleContainerPublisher}
 */
var ConsoleDocumentPublisher = function() {
  ConsoleContainerPublisher.call(this);
};
tsumekusa.inherits(ConsoleDocumentPublisher, ConsoleContainerPublisher);


/** @override */
ConsoleDocumentPublisher.prototype.createHeader = function(doc) {
  return null;
};


/** @override */
ConsoleDocumentPublisher.prototype.createFooter = function(doc) {
  var now = doc.getDate();
  var year = now.getFullYear();
  var month = date.getShortMonth(now);
  var day = now.getDay();

  return [
    string.repeat('-', consoleDoc.TEXT_WIDTH),
    'This reference was generated by Jsdoc with Tsumekusa on ' +
        [year, month, day].join(' '),
    '  Jsdoc3 - https://github.com/jsdoc3/jsdoc',
    '  Tsumekusa - https://github.com/OrgaChem/tsumekusa'
  ].join('\n');
};


// Export the constructor.
module.exports = ConsoleDocumentPublisher;
