// This script licensed under the MIT.
// http://orgachem.mit-license.org


var tsumekusa = require('../../../tsumekusa');
var string = require('../../../tsumekusa/string');
var date = require('../../../tsumekusa/date');
var consoleDoc = require('../../../tsumekusa/consoleDoc');
var ConsoleDocContainerPublisher = require(
    '../../../tsumekusa/publishing/ConsoleDocContainerPublisher');



/**
 * A class for document publisher for console.
 * @constructor
 * @extends {ConsoleDocContainerPublisher}
 */
var ConsoleDocDocumentPublisher = function() {
  ConsoleDocContainerPublisher.call(this);
};
tsumekusa.inherits(ConsoleDocDocumentPublisher, ConsoleDocContainerPublisher);


/** @override */
ConsoleDocDocumentPublisher.prototype.createHeader = function(doc) {
  return null;
};


/** @override */
ConsoleDocDocumentPublisher.prototype.createFooter = function(doc) {
  var now = doc.getDate();
  var year = now.getFullYear();
  var month = date.getShortMonth(now);
  var day = now.getDay();

  return [
    string.repeat('-', consoleDoc.TEXT_WIDTH),
    'This reference was generated by Jsdoc with Tsumekusa on ' +
        [year, month, day].join(' '),
    '  Jsdoc3 - https://github.com/jsdoc3/jsdoc',
    '  Tsumekusa - https://github.com/OrgaChem/tsumekusa'
  ].join('\n');
};


// Export the constructor.
module.exports = ConsoleDocDocumentPublisher;
